name: Bug Report
description: Report a bug or error in the project
title: 'bug: lowercasetitlehere'
labels:
  - bug
projects:
  - nacix/3
assignees:
  - nacix
body:
  - type: markdown
    attributes:
      value: >
        ### Before submitting a bug report, please make sure you are not
        duplicating an existing issue.


        ---
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Briefly describe the problem you encountered.
      placeholder: Describe the problem here...
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Reproduction Steps
      description: Provide a list of steps we can use to reproduce the issue.
      placeholder: (optional) List the steps here...
  - type: dropdown
    id: arma-branch
    attributes:
      label: Arma Branch
      description: >-
        Select which branch of Arma 3 you're running. If you're not sure what
        this means, go with default.
      options:
        - Default
        - Profiling
        - Development
        - Other
    validations:
      required: true
  - type: checkboxes
    id: bug-context
    attributes:
      label: Context
      description: Mark the context(s) in which this bug occured (select all that apply).
      options:
        - label: Singleplayer
          required: false
        - label: Multiplayer
          required: false
        - label: 3DEN
          required: false
        - label: Zeus
          required: false
        - label: Mission
          required: false
        - label: Virtual Arsenal
          required: false
        - label: Other
          required: false
  - type: textarea
    id: media
    attributes:
      label: Media
      description: >-
        If you have any additional media pertaining to this bug (screenshots,
        videos, etc.), please upload it here.
      placeholder: (optional) Upload media here...
  - type: markdown
    attributes:
      value: >-
        # Debug Report (optional)

        If you don't mind some extra hassle, you can provide us with a debug
        report (*.rpt) to help identify the issue.


        You can find a *.RPT file using the following steps:

        1. Open *File Explorer*

        2. Enter `%localappdata%\ Arma 3` in the address bar

        3. Sort by date modified and open the latest file of type `RPT File`


        Once you open the *.RPT, you can paste the contents to
        [pastebin](https://pastebin.com) and provide the shareable link below.
  - type: input
    id: rpt-pastebin
    attributes:
      label: '*.RPT File'
      description: If applicable, provide the pastebin link to your *.RPT output.
      placeholder: (optional) Paste link here...
