name: Tweak Request
description: Suggest a tweak/edit to an existing feature
title: 'tweak: lowercasetitlehere'
labels:
  - tweak
projects:
  - nacix/3
assignees:
  - nacix
body:
  - type: textarea
    id: tweak-description
    attributes:
      label: Tweak Details
      description: Briefly describe the tweak(s) you'd like to see in the project
      placeholder: Describe your tweak(s) here...
    validations:
      required: true
  - type: textarea
    id: tweak-benefits
    attributes:
      label: Tweak Benefits
      description: >-
        Briefly and describe how your tweak(s) would benefit
        the project.
      placeholder: (optional) Sell your tweak(s) here...
  - type: textarea
    id: media
    attributes:
      label: Media
      description: >-
        If you have any additional media (screenshots, videos, etc.) for your
        tweak(s), please upload them here.
      placeholder: (optional) Upload media here...
  - type: input
    id: other-info
    attributes:
      label: Additional Details
      description: Describe any additional comments/concerns.
      placeholder: (optional) Provide additional details here...